name: Sync to iofog-comminty-repo

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace 'AlpaslanDogan' with 'DATASANCE'
        run: |
          find . -type f -not -path "./.git/*" -exec sed -i 's/AlpaslanDogan/DATASANCE/g' {} +

      - name: Commit replacements if any (excluding workflow file)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Eğer değişiklik varsa ve workflow dosyası dışındaysa commit et
          if git diff --quiet -- . ':(exclude).github/workflows/sync-to-community.yml'; then
            echo "No changes to commit."
          else
            git add . ':!./.github/workflows/sync-to-community.yml'
            git commit -m "ci: Replace 'AlpaslanDogan' with 'DATASANCE'"
            git push origin main
          fi

      - name: Push to iofog-comminty-repo
        run: |
          git remote add target https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/alpaslan-datasance/iofog-comminty-repo.git
          git push target main --force
